@api = http://localhost:3000/tasks
GET {{api}}

###
GET {{api}}/1

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
  "title": "task 6",
  "description": " this is the 6 task"
}

###
DELETE  {{api}}/6

###
PUT {{api}}/2
Content-Type: application/json

{
  "description": "old task 2"
}